export const AdsList=() => {
 const ads=  [ {
      category: "Electronics",
      subcategory: "Smartphones",
      adTitle: "Brand New iPhone 14 Pro Max - 256GB",
      askingPrice: 1200,
      description: "Latest iPhone 14 Pro Max with 256GB storage, never used. Comes with original accessories.",
      name: "John Doe",
      organisation: "TechWorld",
      email: "john.doe@example.com",
      phone: "+1 123 456 7890",
      location: "New York",
      city: "New York City",
      town: "Manhattan",
      neighborhood: "Midtown",
      postalCode: "10001",
      expireIn: "30 days",
    },
    {
      category: "Vehicles",
      subcategory: "Cars",
      adTitle: "2019 Toyota Corolla LE - Low Mileage",
      askingPrice: 18000,
      description: "Well-maintained 2019 Toyota Corolla, 40,000 miles, excellent condition.",
      name: "Emma Smith",
      organisation: "Auto Deals",
      email: "emma.smith@example.com",
      phone: "+1 987 654 3210",
      location: "California",
      city: "Los Angeles",
      town: "Hollywood",
      neighborhood: "Sunset Blvd",
      postalCode: "90028",
      expireIn: "45 days",
    },
    {
      category: "Real Estate",
      subcategory: "Apartments for Rent",
      adTitle: "2 BHK Apartment for Rent in Downtown",
      askingPrice: 2500,
      description: "Spacious 2 BHK apartment available for rent in downtown with modern amenities.",
      name: "Michael Johnson",
      organisation: "RealtyHub",
      email: "michael.johnson@example.com",
      phone: "+1 555 678 9012",
      location: "Illinois",
      city: "Chicago",
      town: "Loop",
      neighborhood: "South Loop",
      postalCode: "60605",
      expireIn: "60 days",
    },
    {
      category: "Jobs",
      subcategory: "Software Engineer",
      adTitle: "Hiring Full-Stack Developer - Remote",
      askingPrice: "Negotiable",
      description: "Looking for an experienced full-stack developer with expertise in React and Node.js.",
      name: "Sarah Williams",
      organisation: "Tech Innovators",
      email: "sarah.williams@example.com",
      phone: "+1 444 321 6789",
      location: "Texas",
      city: "Austin",
      town: "Downtown",
      neighborhood: "Tech Park",
      postalCode: "73301",
      expireIn: "90 days",
    },
    {
      category: "Furniture",
      subcategory: "Sofas",
      adTitle: "Luxury Leather Sofa Set - 3 Seater",
      askingPrice: 750,
      description: "High-quality genuine leather sofa, barely used, in excellent condition.",
      name: "David Brown",
      organisation: "Home Decor",
      email: "david.brown@example.com",
      phone: "+1 222 789 6543",
      location: "Florida",
      city: "Miami",
      town: "Brickell",
      neighborhood: "Bayfront",
      postalCode: "33130",
      expireIn: "30 days",
    },
    {
      category: "Services",
      subcategory: "Cleaning",
      adTitle: "Professional Home Cleaning Service",
      askingPrice: "Starting at $50",
      description: "Get your home deep cleaned with our expert cleaning team. Satisfaction guaranteed.",
      name: "Olivia Clark",
      organisation: "CleanSwift",
      email: "olivia.clark@example.com",
      phone: "+1 777 888 9999",
      location: "Washington",
      city: "Seattle",
      town: "Belltown",
      neighborhood: "Downtown Core",
      postalCode: "98121",
      expireIn: "30 days",
    },
    {
      category: "Pets",
      subcategory: "Dogs",
      adTitle: "Golden Retriever Puppies for Sale",
      askingPrice: 1200,
      description: "Healthy Golden Retriever puppies available for loving homes. Vaccinated and dewormed.",
      name: "Daniel Wilson",
      organisation: "Happy Pets",
      email: "daniel.wilson@example.com",
      phone: "+1 999 123 4567",
      location: "Nevada",
      city: "Las Vegas",
      town: "Paradise",
      neighborhood: "Spring Valley",
      postalCode: "89109",
      expireIn: "40 days",
    },
    {
      category: "Fashion",
      subcategory: "Watches",
      adTitle: "Rolex Submariner - Authentic Luxury Watch",
      askingPrice: 9500,
      description: "Pre-owned but well-maintained Rolex Submariner. Comes with original box and papers.",
      name: "Sophia Martinez",
      organisation: "Luxury Timepieces",
      email: "sophia.martinez@example.com",
      phone: "+1 333 555 7777",
      location: "New Jersey",
      city: "Jersey City",
      town: "Downtown",
      neighborhood: "Waterfront",
      postalCode: "07302",
      expireIn: "50 days",
    },
    {
      category: "Electronics",
      subcategory: "Laptops",
      adTitle: "MacBook Pro 16-inch M1 Max - 1TB SSD",
      askingPrice: 2300,
      description: "Lightly used MacBook Pro 16-inch with M1 Max chip. Comes with AppleCare.",
      name: "Ethan Davis",
      organisation: "Tech Masters",
      email: "ethan.davis@example.com",
      phone: "+1 888 222 4444",
      location: "Arizona",
      city: "Phoenix",
      town: "Camelback",
      neighborhood: "Downtown",
      postalCode: "85001",
      expireIn: "35 days",
    },
    {
      category: "Home & Garden",
      subcategory: "Kitchen Appliances",
      adTitle: "Brand New Ninja Air Fryer - 6 Quart",
      askingPrice: 100,
      description: "Ninja Air Fryer, still in the box. Perfect for healthy cooking.",
      name: "Liam White",
      organisation: "Kitchen Essentials",
      email: "liam.white@example.com",
      phone: "+1 666 777 8888",
      location: "Colorado",
      city: "Denver",
      town: "Capitol Hill",
      neighborhood: "Uptown",
      postalCode: "80202",
      expireIn: "20 days",
    },
  ];
}
  export default AdsList;
  